// <auto-generated />
namespace Electronic_G5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alterProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202406101557141_alterProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
