// <auto-generated />
namespace Electronic_G5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddResetPass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddResetPass));
        
        string IMigrationMetadata.Id
        {
            get { return "202406031451044_AddResetPass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
